version: '2.1'
services:

  postgres:
    image: postgres:9.6
    ports:
      - 5432:5432
    command: postgres -c max_connections=1000 -c shared_buffers=1GB
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  redis:
    image: 'redis:5.0.5'

  airflow-web:
    image: puckel/docker-airflow:1.10.4
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      - AIRFLOW__CORE__SQL_ALCHEMY_POOL_SIZE=1000
    volumes:
      - ./requirements.txt:/requirements.txt
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/plugins:/usr/local/airflow/plugins
    ports:
      - 8080:8080
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  airflow-flower:
    image: puckel/docker-airflow:1.10.4
    restart: always
    depends_on:
      - redis
    environment:
      - EXECUTOR=Celery
      - AIRFLOW__CORE__SQL_ALCHEMY_POOL_SIZE=1000
    ports:
      - "5555:5555"
    command: flower

  airflow-scheduler:
    image: puckel/docker-airflow:1.10.4
    restart: always
    depends_on:
      - airflow-web
    volumes:
      - ./requirements.txt:/requirements.txt
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/plugins:/usr/local/airflow/plugins
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      - AIRFLOW__CORE__SQL_ALCHEMY_POOL_SIZE=1000
    command: scheduler

  airflow-worker:
    image: puckel/docker-airflow:1.10.4
    restart: always
    depends_on:
      - airflow-scheduler
    volumes:
      - ./requirements.txt:/requirements.txt
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/plugins:/usr/local/airflow/plugins
    environment:
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      - AIRFLOW__CORE__SQL_ALCHEMY_POOL_SIZE=1000
    command: worker
